apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-custom
rules:
  - apiGroups: ["*"]   # Allows access to all API groups
    resources: ["*"]    # Grants access to all resources (pods, services, deployments, etc.)
    verbs: ["*"]        # Grants all actions (get, list, create, update, delete, patch, watch, etc.)